apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      version: "51.1.0" # Specify the desired version
  values:
    # Customize your values here
    prometheus:
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false
